# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Readaloud < Formula
  desc "readaloud is a command-line tool for text-to-speech synthesis using Microsoft Edge's online service."
  homepage "https://github.com/kennyparsons/readaloud"
  version "1.2.0"
  license "ISC"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/kennyparsons/readaloud/releases/download/v1.2.0/readaloud_Darwin_x86_64.tar.gz"
    sha256 "46d43f6b421387e2fd96a2370983feef5390aed8fb6fbb879dcbacec1195ea40"

    def install
      bin.install "readaloud"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/kennyparsons/readaloud/releases/download/v1.2.0/readaloud_Darwin_arm64.tar.gz"
    sha256 "49255504e1124a27ba99f12e79577a1c775f403c9e0b5c17541cf317b6ded6b2"

    def install
      bin.install "readaloud"
    end
  end
end
